name: Variáveis GitHub

on:
  push:
    branches:
      - main

jobs:
  laboratorio:
    runs-on: ubuntu-latest

    env:
      APP_NAME: docker-nginx-php
      AMBIENTE: desenvolvimento

    steps:

      - uses: actions/checkout@v4

      - name: Variáveis criadas por nós
        run: |
          echo "Aplicação: $APP_NAME"
          echo "Ambiente: $AMBIENTE"

      - name: Informações do GitHub
        run: |
          echo "Usuário: ${{ github.actor }}"
          echo "Repositório: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"

      - name: Data
        run: date
