name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validar Compose
        run: docker compose config

  build:

    needs: validate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker compose build

  info:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Informações
        run: |
          echo "Workflow concluído com sucesso!"
          echo "Runner: $RUNNER_OS"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
