name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Mostrar Docker
        run: docker --version

      - name: Mostrar Docker Compose
        run: docker compose version

      - name: Validar docker-compose.yml
        run: docker compose config

      - name: Construir containers
        run: docker compose build
